### ISSUE TITLE
High CPU usage when this plugin is enabled

### ISSUE THREAD

**Issue by xhpohanka** [SublimeText/TrailingSpaces#144]
I see a high CPU usage (around 15-20%) with TrailingSpaces enabled, even when sublime is on background. My operating system is Arch Linux, sublime-text-dev package...

**Comment by rchl** [comment]
What kind of CPU do you have?
Does the problem persist after ST restart?
Does it happen right away after restart or after using ST for some time?

**Comment by xhpohanka** [comment]
> What kind of CPU do you have?

Intel(R) Core(TM) i7-8565U CPU
> Does the problem persist after ST restart?

Yes
> Does it happen right away after restart or after using ST for some time?

On my setup it is perfectly reproducible, the CPU is stressed whole time since starting ST. It goes back to normal when I add TrailingSpaces into ignored packages...

**Comment by rchl** [comment]
There is a `update_interval` setting (by default set to 250ms) that you can try changing to something much higher just to confirm that it's that causing the issue.

**Comment by xhpohanka** [comment]
It really seems that it is related. When setting `update_interval` to 25000 I have a 20% peak on CPU usage each 25 seconds :)

**Comment by rchl** [comment]
- Does it reproduce on any file being focused? Even something extreme like a view with one word?
- Have you customized any TrailingSpaces settings? Can you post them if so?

I can see something like this with TS enabled:
![Screenshot 2020-05-18 at 23 16 11](https://user-images.githubusercontent.com/153197/82260485-a2c43f80-995d-11ea-9cd2-7bfae5856695.png)

So CPU usage jumps up and then slowly gets lower until it jumps up again. And that's over many seconds, with a default 250ms interval. It seems weird to me.

**Comment by xhpohanka** [comment]
I see similar behavior as you - CPU usage peaks and then it is slowly decreasing, then peaks again.
When there is no file opened CPU is low as well as with file with no syntax enabled.

**Comment by rchl** [comment]
Create ST issue for it https://github.com/sublimehq/sublime_text/issues/3353

**Comment by NhoNho** [comment]
I was also experiencing a continuous high CPU load in ST3. After trying a lot of things, I finally narrowed it down to this plugin. Setting a high update_interval (10s) seems to work, thanks

**Comment by rchl** [comment]
This is fixed in the latest dev builds of ST4 (see https://github.com/sublimehq/sublime_text/issues/3353) so I'm closing this issue also.

Unfortunately, it's not likely that ST3 will receive the same fix.

**Comment by garymoon** [comment]
Just to be sure I understand, there's a bug in ST causing this, it's been fixed in the latest dev release, but the same fix won't be applied to the current stable release, and now the bug is closed?

**Comment by rchl** [comment]
Yes. The solution for ST3 users is to increase the `update_interval` value to minimize the issue.

**Comment by garymoon** [comment]
I guess I have to appreciate the honesty? :man_shrugging: Thanks @rchl.

**Comment by dcanuhe** [comment]
@garymoon: reverting to `e24719053fe6960a327591d2c48ccbd49684500d` fixed this issue for me. It's not ideal, but it works.

**Comment by mkj** [comment]
I'm still seeing constant idle CPU with ST4 4105, the old rev `e24719053fe6960a327591d2c48ccbd49684500d` seems to work OK, I'm fine using that. Just as a data point.
